version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres-distcomp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distcomp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d distcomp" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: dc
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app/src
    ports:
      - "24110:24110"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/distcomp?options=-csearch_path%3Ddistcomp,public
        - POSTGRES_HOST=postgres
        - POSTGRES_DB=distcomp
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:24110 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data: